### PR TITLE
Implement SetMode() and Disable() methods.

### PR DESCRIPTION
**Pull request by ptobuon**
Only work in SVGAIICanvas.

### CODE REVIEW

**Comment by terminal-cs** [comment]
Hello, could you please follow the code styling guidelines? Also it seems you are using different formatting for spacing, which isn't how the rest of the code is. I recommend fixing that because it also completely screws up the github diff viewer

**Comment by terminal-cs** [comment]
Nevermind, i can change it for you

**Comment by ptobuon** [comment]
Thanks

**Comment by terminal-cs** [comment]
> Thanks and sorry.

No problem. Can you give me write access to your fork so I can commit my changes?

**Comment by terminal-cs** [comment]
I removed SetMode() because the base displays can override the width and height properties and set modes that way, and Disable is no IsEnabled which can be set to true or false.

**Comment by terminal-cs** [comment]
Thanks for the PR!

**Pull request merged**
