### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by theopcoder**
I redid the website to make it more pleasant to look at and make it feel and look a bit more modern. What do you think? This is what it looks like: 
image

Let me know of any changes or ideas you would like me to add!

### CODE REVIEW

**Comment by theopcoder** [comment]
Also, is there an official image/emojicon that you would like me to use for the website?

**Comment by theopcoder** [comment]
Hello?

**Comment by terminal-cs** [comment]
Hello, sorry for the delay. I haven't been on lately. You can use these two logos for the site: 
Adobe_Post_20210828_1343320 005324055727642607
Adobe_Post_20210828_1343400 09098068592350006

**Comment by terminal-cs** [comment]
also I don't quite like the old style font currently, are there any other fonts you could try?

**Comment by terminal-cs** [comment]
Also on the GitHub button, you should add a GitHub icon next to it

**Comment by theopcoder** [comment]
I will add the picture for the website, I can add the github picture next to the button, and send me some choices you would like to see for fonts for the website!

**Comment by terminal-cs** [comment]
> I will add the picture for the website, I can add the github picture next to the button, and send me some choices you would like to see for fonts for the website!

I don't have any specific ones in mind, just ones you think would look nice. But could you send a screenshot of what it would look like with the comfortaa font?

**Comment by theopcoder** [comment]
The font comfortaa doesn't seem to be a font. Perhaps you misspelled?

**Comment by theopcoder** [comment]
Also, this is what the tab looks like the favicon 
image

**Comment by terminal-cs** [comment]
> The font comfortaa doesn't seem to be a font. Perhaps you misspelled?

No I've used it before, it's not used alot so might take a second to find it

**Comment by terminal-cs** [comment]
> Also, this is what the tab looks like the favicon 
> image
> 

Image looks a bit small.. hm

**Comment by theopcoder** [comment]
> > The font comfortaa doesn't seem to be a font. Perhaps you misspelled?
> 
> No I've used it before, it's not used alot so might take a second to find it

I'm coding in Visual Studio Code. Ill see if I might be able to import it using something

**Comment by theopcoder** [comment]
> > Also, this is what the tab looks like the favicon
> > image
> 
> Image looks a bit small.. hm

If you could enlarge the photo, that might help

**Comment by theopcoder** [comment]
Quick question, do you want the font to be fancier, look more like hand writing? Any details are awesome!

**Comment by terminal-cs** [comment]
> > > Also, this is what the tab looks like the favicon
> > > image
> > 
> > Image looks a bit small.. hm
> 
> If you could enlarge the photo, that might help

It's already atleast 1080p

**Comment by theopcoder** [comment]
Do you have Discord or something that we chat easier?

**Comment by terminal-cs** [comment]
> Do you have Discord or something that we chat easier?

Yes: @Terminal.cs#4512

**Comment by theopcoder** [comment]
Alright

**Comment by theopcoder** [comment]
I sent the friend request.

**Pull request merged**
