### PR TITLE
Update PrismAPI.csproj

### PR DESCRIPTION
**Pull request by zarlo**
allow it to be built as a nuget package

### CODE REVIEW

**Comment by terminal-cs** [comment]
Thanks, could you switch the two bottom ones around to maintain descending length in the file, and change auther to "The Prism Project"?

**Comment by terminal-cs** [comment]
Also title is duplicated

**Comment by zarlo** [comment]
> Also title is duplicated

o that it is

**Comment by terminal-cs** [comment]
Cool, thanks! I might upload this later when I've got time

**Pull request merged**
