### PR TITLE
New website

### PR DESCRIPTION
**Pull request by Pyogenics**
Still WIP ofc and I also have some changes I haven't committed yet sitting in a local repo.

### CODE REVIEW

**Comment by Pyogenics** [comment]
Will commit some final changes this week.

**Comment by Pyogenics** [comment]
I need to review the mobile layout stuff, will likely remove it for now and re add in a later pull request in a more finished form.

**Comment by terminal-cs** [comment]
😴

**Comment by Pyogenics** [comment]
Wrote abit for contrib building.

**Comment by Pyogenics** [comment]
All done.

**Comment by terminal-cs** [comment]
What is wrong
image

**Comment by Pyogenics** [comment]
There were additional commits added to the GH pages branch whilst this fork was being worked on. There is a miss match in commit history.

**Comment by Pyogenics** [comment]
I might be able to fix that on my end

**Comment by Pyogenics** [comment]
I'm not experienced enough with git lmao

**Pull request merged**
